# Generated by Django 3.1.3 on 2020-12-26 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djangolearn.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('pl', 'Polish')], max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z ]+$', flags=re.RegexFlag['IGNORECASE'])])),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_translated_text', models.TextField(verbose_name='non_translated_text')),
                ('translated_text', models.TextField(verbose_name='translated_text')),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='priority')),
                ('image', models.ImageField(blank=True, upload_to=djangolearn.models.get_upload_path, verbose_name='image')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangolearn.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'phrase',
                'verbose_name_plural': 'phrases',
                'ordering': ['language'],
            },
        ),
    ]
