# Generated by Django 3.1.3 on 2020-12-03 18:31

import catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_nauthor_nbook_npublisher_nstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Write your comment. 1000 characters max', max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max 30 character title for your image', max_length=30)),
                ('description', models.CharField(help_text='Max 150 character description of your image', max_length=150)),
                ('image', models.ImageField(upload_to=catalog.models.UploadedImage.get_upload_path)),
                ('upload_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
        migrations.DeleteModel(
            name='nAuthor',
        ),
        migrations.RemoveField(
            model_name='nbook',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='nbook',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='nstore',
            name='books',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='nBook',
        ),
        migrations.DeleteModel(
            name='nPublisher',
        ),
        migrations.DeleteModel(
            name='nStore',
        ),
        migrations.AddField(
            model_name='comment',
            name='uploaded_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.uploadedimage'),
        ),
    ]
