# Generated by Django 3.1.3 on 2020-12-22 19:43

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201203_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='description',
            field=models.CharField(help_text='Required.Max 150 character description of your image', max_length=150),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(help_text='Max. file size: 16777216', upload_to=catalog.models.UploadedImage.get_upload_path, validators=[catalog.models.file_size_validator]),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(help_text='Required. Max 30 character title for your image', max_length=30),
        ),
    ]
